### ISSUE TITLE
How to change the popover size?

### ISSUE THREAD

**Issue by thedahiyaboy** [eilianlove/PopoverKit#2]
My app popover table Height is different for iPhone and iPad, so how to change popover size and even,  table view is also not scrolling.

**Comment by ZionChang** [comment]
The height of PopoverTableViewController is depending on preferredContentSize which is calculated by rows of tableview

**Comment by thedahiyaboy** [comment]
Please check the below screen shots for iPhone & iPad of popovercontroller. In iPad list is cropped and tableView is not scrolling.

P.S. I am using the same TableView that is in the demo that you have provided with same model data structure.
 
and for row height I am doing below code

```
public override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return DeviceType.isIPad() ? 50 : 40
    }

```

If i Change the height from here then popover tableView row height will be changed as expected but the Popover Height is not changed and it cropped the options in Popover.

![ipad](https://user-images.githubusercontent.com/22885093/52633540-c68f0f00-2eea-11e9-80c1-f88d9cc25118.png)
![iphone](https://user-images.githubusercontent.com/22885093/52633542-c727a580-2eea-11e9-8f97-f56af95eca01.png)

**Comment by ZionChang** [comment]
I have checked out, I didn't find any problem, sorry. If you really want to change the height of popover, you can inherit PopoverTableViewController, and override preferredContentSize and heightForRow. Finally if there has any problem, you can send me demo using email.

**Comment by thedahiyaboy** [comment]
Please check the [Repo](https://github.com/thedahiyaboy/DummyPopover). 

I have tried this below line to change the contentsize but there is no effect (for dummy check).
`vc.preferredContentSize = CGSize(width: 250, height: 500)`

I have observed one more thing, if I removed `heightForRowAt` then all titles are shown perfectly and popOver kit width & height will be based on the title size. 

I want  popover kit size different in iPhone and iPad.

**Comment by ZionChang** [comment]
Please try

```swift
class CustomPopoverTableViewController: PopoverTableViewController {
    
    override public var preferredContentSize: CGSize {
        get {
            return CGSize(width: 250, height: 250)
        }
        set {
            super.preferredContentSize = newValue
        }
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        tableView.isScrollEnabled = true
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 100
    }
    
}
```

And then exchange the PopoverTableViewController with CustomPopoverTableViewController

**Comment by thedahiyaboy** [comment]
It works as expected. Is there any way to get total count of array in get method of preferredContentSize so that I can set size dynamically instead of static value.

**Comment by thedahiyaboy** [comment]
> Please try
> 
> ```swift
> class CustomPopoverTableViewController: PopoverTableViewController {
>     
>     override public var preferredContentSize: CGSize {
>         get {
>             return CGSize(width: 250, height: 250)
>         }
>         set {
>             super.preferredContentSize = newValue
>         }
>     }
> 
>     override func viewDidLoad() {
>         super.viewDidLoad()
>         tableView.isScrollEnabled = true
>     }
>     
>     override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
>         return 100
>     }
>     
> }
> ```
> 
> And then exchange the PopoverTableViewController with CustomPopoverTableViewController

Working as expected , Thanks
