### ISSUE TITLE
Add action for customview on viewcontroller

### ISSUE THREAD

**Issue by syafieqq** [eilianlove/PopoverKit#3]
HI, i just want to use custom view for the popover, but failed to call the delegate method.

        @IBAction func didClickCustomButton(_ sender: UIButton) {
            let vc = PopoverTableViewController(items: [customModel])
            vc.pop.isNeedPopover = true
            vc.pop.popoverPresentationController?.sourceView = sender
            vc.pop.popoverPresentationController?.sourceRect = sender.bounds
            vc.pop.popoverPresentationController?.arrowDirection = .up
            vc.delegate = self
            AjustFontPopoverCell().delegate = self
            present(vc, animated: true, completion: nil)  
        }
        
        extension ViewController: PopoverTableViewControllerDelegate, AjustFontPopoverCellDelegate {
            func didClickMediumButton(in cell: AjustFontPopoverCell) {
                print ("enter Medium")
            }
    
            func didClickLargeButton(in cell: AjustFontPopoverCell) {
                print ("enter Large")
            }
    
            func didClickExtraLargeButton(in cell: AjustFontPopoverCell) {
                print ("enter XL")
            }
         }

is it any demo to use the action button of the buttons for Custom class

**Comment by ZionChang** [comment]
Hi:
   You can change the CustomModel to class which can conform the Protocol, then just like this

```swift
/// Custom
class CustomModel: PopoverCellConfiguration, AjustFontPopoverCellDelegate {
   
    public var width: CGFloat {
        let cell = AjustFontPopoverCell()
        config(cell: cell)
        let width = cell.systemLayoutSizeFitting(UILayoutFittingCompressedSize).width
        return width
    }
    
    public var resuable: PopoverCellResuable.Type {
        return AjustFontPopoverCell.self
    }
    
    public func config(cell: UITableViewCell) {
        guard cell is AjustFontPopoverCell else {
            return
        }
        // config delegate...
        (cell as! AjustFontPopoverCell).delegate = self
    }
    
    func didClickLargeButton(in cell: AjustFontPopoverCell) {
        print(#function, #line, type(of: self))
    }
    
    func didClickMediumButton(in cell: AjustFontPopoverCell) {
        print(#function, #line, type(of: self))
    }
    
    func didClickExtraLargeButton(in cell: AjustFontPopoverCell) {
        print(#function, #line, type(of: self))
    }
}

```

Or you can make a variable in CustomModel, then others can access it. BTW, closure is also ok. 
You can choose one.

**Comment by syafieqq** [comment]
thanks bro, working well now,, just change struct to class. Thanks alot
